/*
 * Copyright (c) 2016 Intel Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stdio.h>
#include <zephyr/kernel.h>
//#include <zephyr/drivers/gpio.h>
#include <zephyr/drivers/sensor.h>
#include <zephyr/logging/log.h>
#include <zephyr/rtio/rtio.h>


LOG_MODULE_REGISTER(playground_app, LOG_LEVEL_INF);
// debug
//#include <zephyr/sys/printk.h>
#include "vl53l8cx_debug.h"

#define DEFAULT_SAMPLE_FREQ_HZ 10
#define DEFAULT_ZONE_CNT 16 // 16 or 64

/* 
 * 1. Define RTIO context with a dedicated Memory Pool.
 * Args: name, sq_size (pow 2), cq_size (pow 2), mem_blocks, block_byte_size, alignment 
 */
RTIO_DEFINE_WITH_MEMPOOL(
    tof_rtio_ctx,           // name
    8,                      // sq size
    8,                      // cq size
    16,                     // num of blocks
    DEFAULT_ZONE_CNT * 2,   // block size, 2 bytes per zone
    sizeof(void *)          // byte aligne
);

SENSOR_DT_READ_IODEV(
    tof_iodev, 
    DT_INST(0, st_vl53l8cx), 
    { SENSOR_CHAN_DISTANCE, DEFAULT_ZONE_CNT }
);

int main(void)
{
	int ret;
    const uint32_t BUFF_DEBUG_SIZE = 100;
    uint8_t buff[BUFF_DEBUG_SIZE];

	//printk("RAW PRINTK: Entering main\n");

	LOG_INF("START ----");

	const struct device *dev = DEVICE_DT_GET_ONE(st_vl53l8cx);

    if (!device_is_ready(dev)) {
        LOG_INF("dev NOT ready");
        return 0;
    }
	LOG_INF("%s ready", dev->name);

    // resolution
    struct sensor_value resolution = { .val1 = DEFAULT_ZONE_CNT, .val2 = 0 };
    LOG_INF("Setting resolution to %d Hz...", resolution.val1);
    sensor_attr_set(
        dev, 
        SENSOR_CHAN_DISTANCE, 
        SENSOR_ATTR_RESOLUTION, 
        &resolution
    );
    if (ret != 0) {
        LOG_ERR("Failed to set resolution (error %d)", ret);
    }

    ret = sensor_attr_get(
        dev, 
        SENSOR_CHAN_DISTANCE, 
        SENSOR_ATTR_RESOLUTION, 
        &resolution
    );
    if (ret != 0) {
        LOG_ERR("Failed to get resolution (error %d)", ret);
    }
    LOG_INF("Read back resolution: %d", resolution.val1);

    // sample freq, starts sampling if freq > 0
    struct sensor_value sample_freq = { .val1 = DEFAULT_SAMPLE_FREQ_HZ, .val2 = 0 };
    LOG_INF("Setting frequency to %d Hz...", sample_freq.val1);
    ret = sensor_attr_set(
        dev, 
        SENSOR_CHAN_DISTANCE, 
        SENSOR_ATTR_SAMPLING_FREQUENCY, 
        &sample_freq
    );
    if (ret != 0) {
        LOG_ERR("Failed to set sample frequency (error %d)", ret);
    }
    ret = sensor_attr_get(
        dev, 
        SENSOR_CHAN_DISTANCE, 
        SENSOR_ATTR_SAMPLING_FREQUENCY, 
        &sample_freq
    );
    if (ret != 0) {
        LOG_ERR("Failed to get sample frequency (error %d)", ret);
    }
    LOG_INF("Read back sample freq: %d", sample_freq.val1);

    // decoder
    const struct sensor_decoder_api *decoder;
    sensor_get_decoder(dev, &decoder);
#if 1
    // trigger
    //struct sensor_trigger trig = {
    //    .type = SENSOR_TRIG_DATA_READY,
    //    .chan = SENSOR_CHAN_DISTANCE,
    //};
    ///* Register the ISR */
    //if (sensor_trigger_set(dev, &trig, vl53l8cx_rdy_callback) < 0) {
    //    return -EIO;
    //}
    ///////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////
    struct rtio_cqe *cqe;
    uint8_t *buf;
	uint32_t buf_len;
    struct sensor_chan_spec ch_spec = { SENSOR_CHAN_DISTANCE, 0 };
    int16_t fake_data_out[64];

    while (true) {
        /* Queue async read to the RTIO context; uses RTIO mempool for allocation */
		ret = sensor_read_async_mempool(&tof_iodev, &tof_rtio_ctx, NULL);
		if (ret < 0) {
			LOG_ERR("Failed to submit read: %d", ret);
			continue;
		}

		/* Block and consume the completion event */
#if 0
		cqe = rtio_cqe_consume_block(&tof_rtio_ctx);
#endif
        cqe = rtio_cqe_consume(&tof_rtio_ctx);
        while (cqe == 0) {
            LOG_INF(" ... ");
            k_sleep(K_MSEC(10));
            cqe = rtio_cqe_consume(&tof_rtio_ctx);
        }

		if (cqe->result < 0) {
			LOG_ERR(" *** Read failed with result: %d", cqe->result);
			rtio_cqe_release(&tof_rtio_ctx, cqe);
			continue;
		}

		/* Pull buffer pointer generated by the driver's rx_buf pool execution */
		ret = rtio_cqe_get_mempool_buffer(&tof_rtio_ctx, cqe, &buf, &buf_len);
		if (ret == 0) {
			uint32_t fit = 0;
			ret = decoder->decode(buf, ch_spec, &fit, 1, &fake_data_out);

            /////
            LOG_INF("%d Got data: %d %d %d %d .. %d", 
                ret, fake_data_out[0], fake_data_out[1], fake_data_out[2], fake_data_out[3], fake_data_out[15]);

			rtio_release_buffer(&tof_rtio_ctx, buf, buf_len);
		}

		rtio_cqe_release(&tof_rtio_ctx, cqe);
        //LOG_INF("------");
		k_sleep(K_MSEC(1000));
    }
#endif

#if 0
    while (true) {
        //k_msleep(10000);
        //LOG_INF("mmmmmmmmm ----");
        test_read(dev, buff, BUFF_DEBUG_SIZE);
    }
	return 0;
#endif
}
